spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  #
  #  ##GATEWAY CONFIGURATIONS
  #
  cloud:
    gateway:
      routes:
        #        ## service1
        - id: ServiceOne
          #uri: lb://service1
          uri: http://localhost:2222/
          predicates:
            - Path=/ServiceOne/** #same name as that of service 1 controller request mapping
        #          filters:
        #            - StripPrefix=1
        #
        #        ## Service2
        - id: ServiceTwo
          # uri: lb://service2
          uri: http://localhost:3333/
          predicates:
            - Path=/ServiceTwo/**  #same name as that of service 2 controller request mapping
#          filters:
#            - StripPrefix=1     #use filters when I want to use filters
server:
  port: 4444
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka




##For application.properties:
  ##----Yet to work on it
# server.port=4444
# spring.application.name=ApiGateWay
# spring.main.web-application-type=reactive
# eureka.instance.hostname=localhost
# eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/

  # Cloud Gateway
  ## For Service One and Service Two
# spring.cloud.gateway.routes[0].id=ServiceOne
# spring.cloud.gateway.routes[0].uri=lb://ServiceOne
# spring.cloud.gateway.routes[0].predicates[0]=Path=/ServiceOne/**
# spring.cloud.gateway.routes[1].id=ServiceTwo
# spring.cloud.gateway.routes[1].uri=lb://ServiceTwo
# spring.cloud.gateway.routes[1].predicates[0]=Path=/ServiceTwo/**

## For department-service and employee-service
#spring.cloud.gateway.routes[0].id=department-service
#spring.cloud.gateway.routes[0].uri=http://localhost:9002/
#spring.cloud.gateway.routes[0].predicates[0]=Path=/departments/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
#spring.cloud.gateway.routes[1].id=employee-service
#spring.cloud.gateway.routes[1].uri=http://localhost:9003/
#spring.cloud.gateway.routes[1].predicates[0]=Path=/employees/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1